apiVersion: v1
kind: Pod
metadata:
  name: pytorch-pod
spec:
  containers:
    - name: pytorch
      image: docker.io/pytorch/pytorch:latest
      command:
        - sleep
        - "infinity"
      tty: true
      stdin: true
      volumeMounts:
        - mountPath: /mnt/shared
          name: shared-volume
  volumes:
    - name: shared-volume
      hostPath:
        path: /Users/ivan/Desktop/DataConteiners
        type: Directory
